"""empty message

Revision ID: 38ede1ff7336
Revises: 5e94a10fcb1b
Create Date: 2022-08-28 11:43:22.039298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ede1ff7336'
down_revision = '5e94a10fcb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direction', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction', sa.Column('order', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
