"""empty message

Revision ID: 5e94a10fcb1b
Revises: 62f01d8cad6e
Create Date: 2022-08-27 21:18:41.141833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e94a10fcb1b'
down_revision = '62f01d8cad6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image')
    # ### end Alembic commands ###
