"""empty message

Revision ID: 62f01d8cad6e
Revises: 
Create Date: 2022-08-27 18:16:42.735838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f01d8cad6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_name', sa.String(length=100), nullable=True),
    sa.Column('ru_name', sa.String(length=100), nullable=True),
    sa.Column('en_name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_name', sa.String(length=100), nullable=True),
    sa.Column('ru_name', sa.String(length=100), nullable=True),
    sa.Column('en_name', sa.String(length=100), nullable=True),
    sa.Column('uz_position', sa.String(length=100), nullable=True),
    sa.Column('ru_position', sa.String(length=100), nullable=True),
    sa.Column('en_position', sa.String(length=100), nullable=True),
    sa.Column('facebook', sa.String(length=50), nullable=True),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_organization', sa.String(length=100), nullable=True),
    sa.Column('ru_organization', sa.String(length=100), nullable=True),
    sa.Column('en_organization', sa.String(length=100), nullable=True),
    sa.Column('uz_number', sa.String(length=100), nullable=True),
    sa.Column('ru_number', sa.String(length=100), nullable=True),
    sa.Column('en_number', sa.String(length=100), nullable=True),
    sa.Column('uz_ques', sa.String(length=100), nullable=True),
    sa.Column('ru_ques', sa.String(length=100), nullable=True),
    sa.Column('en_ques', sa.String(length=100), nullable=True),
    sa.Column('uz_submit', sa.String(length=100), nullable=True),
    sa.Column('ru_submit', sa.String(length=100), nullable=True),
    sa.Column('en_submit', sa.String(length=100), nullable=True),
    sa.Column('uz_address', sa.String(length=100), nullable=True),
    sa.Column('ru_address', sa.String(length=100), nullable=True),
    sa.Column('en_address', sa.String(length=100), nullable=True),
    sa.Column('uz_tel', sa.String(length=100), nullable=True),
    sa.Column('ru_tel', sa.String(length=100), nullable=True),
    sa.Column('en_tel', sa.String(length=100), nullable=True),
    sa.Column('uz_email', sa.String(length=100), nullable=True),
    sa.Column('ru_email', sa.String(length=100), nullable=True),
    sa.Column('en_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_title', sa.String(length=100), nullable=True),
    sa.Column('ru_title', sa.String(length=100), nullable=True),
    sa.Column('en_title', sa.String(length=100), nullable=True),
    sa.Column('uz_text', sa.String(length=100), nullable=True),
    sa.Column('ru_text', sa.String(length=100), nullable=True),
    sa.Column('en_text', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_name', sa.String(length=100), nullable=True),
    sa.Column('ru_name', sa.String(length=100), nullable=True),
    sa.Column('en_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_title', sa.String(length=100), nullable=True),
    sa.Column('ru_title', sa.String(length=100), nullable=True),
    sa.Column('en_title', sa.String(length=100), nullable=True),
    sa.Column('uz_text', sa.String(length=100), nullable=True),
    sa.Column('ru_text', sa.String(length=100), nullable=True),
    sa.Column('en_text', sa.String(length=100), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_title', sa.String(length=100), nullable=True),
    sa.Column('ru_title', sa.String(length=100), nullable=True),
    sa.Column('en_title', sa.String(length=100), nullable=True),
    sa.Column('uz_text', sa.String(length=150), nullable=True),
    sa.Column('ru_text', sa.String(length=150), nullable=True),
    sa.Column('en_text', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uz_ques', sa.String(length=100), nullable=True),
    sa.Column('ru_ques', sa.String(length=100), nullable=True),
    sa.Column('en_ques', sa.String(length=100), nullable=True),
    sa.Column('uz_answer', sa.Text(length=100), nullable=True),
    sa.Column('ru_answer', sa.Text(length=100), nullable=True),
    sa.Column('en_answer', sa.Text(length=100), nullable=True),
    sa.Column('slider_class', sa.Boolean(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direction'], ['direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers')
    op.drop_table('smc')
    op.drop_table('services')
    op.drop_table('news')
    op.drop_table('menu')
    op.drop_table('links')
    op.drop_table('form')
    op.drop_table('events')
    op.drop_table('direction')
    # ### end Alembic commands ###
