"""empty message

Revision ID: 935973dcfefb
Revises: 38ede1ff7336
Create Date: 2022-08-29 02:00:13.789831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935973dcfefb'
down_revision = '38ede1ff7336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uz_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uz_organization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_organization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_organization', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_ques', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_ques', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_ques', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_submit', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_submit', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_submit', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_tel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_tel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_tel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uz_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ru_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('en_email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
